services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bankapp-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  aibankapp:
    build: .
    env_file:
      - .env
    ports:
      - "${BANKAPP_PORT}:8080"
    container_name: aibankapp
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bankapp-net
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - bankapp-net

  ollama-pull-model:
    image: ollama/ollama:latest
    container_name: ollama-pull-model
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      - ollama
    entrypoint: [ "/bin/sh", "-c", "sleep 5 && ollama pull llama3.2" ]
    networks:
      - bankapp-net
  
volumes:
  mysql_data:
  ollama_data:
networks:
  bankapp-net:
    name: bankapp-net

